function S1 = importfile(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   S2 = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   S2 = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   S2 = importfile1('S1.DAT', 1, 147);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/04/09 09:39:20

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format for each line of text:
%   column1: text (%s)
%	column2: text (%s)
%   column3: text (%s)
%	column4: text (%s)
%   column5: text (%s)
%	column6: text (%s)
%   column7: text (%s)
%	column8: text (%s)
%   column9: text (%s)
%	column10: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
S1 = table;
S1.s1 = cellstr(dataArray{:, 1});
S1.Subject = cellstr(dataArray{:, 2});
S1.Code = cellstr(dataArray{:, 3});
S1.VarName4 = cellstr(dataArray{:, 4});
S1.VarName5 = cellstr(dataArray{:, 5});
S1.VarName6 = cellstr(dataArray{:, 6});
S1.VarName7 = cellstr(dataArray{:, 7});
S1.VarName8 = cellstr(dataArray{:, 8});
S1.VarName9 = cellstr(dataArray{:, 9});
S1.VarName10 = cellstr(dataArray{:, 10});

